### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by rrsaikat** [varungulatii/Kdownloader#3]
`FATAL EXCEPTION: pool-3-thread-1
                                                                                                    Process: com.rezwan.downloadertest, PID: 8526
                                                                                                    java.lang.IllegalArgumentException: com.rezwan.downloadertest: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:402)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:672)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:659)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
                                                                                                    	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-07-11 12:20:06.821  8526-9225  eads.downloader         com.rezwan.downloadertest       E  Loaded layer handle (18059192700706006123) for layer /my_product/lib64/libcolorx-loader.so`

**Comment by rrsaikat** [comment]
Fixed by myself!
